SimpleAuthentication/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),

    # Reset complete url not included in `accouts url` due to pre-developed django functions
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password-reset-complete.html',), {
    },
        name='password_reset_complete'
    ),
]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('logout/', views.logout_user, name='logout'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password-reset-sent.html'), name='password-reset-done'
    ),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password-reset-confirm.html'), {
    },
        name='password-reset-confirm'
    ),
    path('password-reset/', views.PasswordResetRequest.as_view(), name='password-reset'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, PermissionsMixin, UserManager
from django.utils.translation import gettext_lazy as _

import uuid


class User(AbstractUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(_('Email Address'), blank=True, unique=True)
    username = models.CharField(_('Username'), max_length=250, unique=True, blank=True, )
    avatar = models.ImageField(null=True, blank=True)
    first_name = models.CharField(_('First Name'), max_length=50, blank=True)
    last_name = models.CharField(_('Last Name'), max_length=50, blank=True)
    date_joined = models.DateTimeField(_('Date Joined'), auto_now=True)
    is_active = models.BooleanField(
        _('Active'), default=True,
        help_text=_(
            'Designates whether a user should be treated as `is active`.'
            'Unselect this instead of manually deleting accounts.'
        ),
    )
    is_staff = models.BooleanField(
        _('Staff'), default=False,
        help_text=_('Designates whether a user can log into the admin site.')
    )
    is_admin = models.BooleanField(default=False)

    # Specify authentication method
    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['username', ]

    def __str__(self):
        return self.email

    objects = UserManager()

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

# Get user model currently in use
User = get_user_model()


class UserLoginForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput, required=True, label='Password',
    )
    remember_me = forms.BooleanField(
        widget=forms.CheckboxInput, required=False, label='Remember me'
    )

    class Meta:
        model = User
        fields = ('email',)
        required = ('email',)
        labels = {
            'email': _('Email Address'),
        }


class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Enter Password', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(
        label='Confirmation Password', widget=forms.PasswordInput, required=True,
        help_text='Passwords are case-sensitive.',
    )

    class Meta:
        model = User
        fields = ('email', 'username',)
        required = ('email', 'username',)
        labels = {
            'email': _('Email Address'),
        }
        help_texts = {
            'email': _('An email will be sent to the address for verification.'),
            'username': _('Username may contain letters, numbers and symbols.'),
        }

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import send_mail, BadHeaderError
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views import generic
from django.utils.translation import gettext_lazy as _
from django.contrib.sites.shortcuts import get_current_site

from accounts.forms import UserLoginForm, UserRegistrationForm

User = get_user_model()

"""
Pre-coded Class-Based and Function-Based Views for login, logout, registration,
home (index) and user password reset operations.
- Home CBV: returns user to the sites home page
- logout FBV: logs out user and returns to login page
- PasswordResetRequest CBV: returns a blank reset form and sends a reset email
- LoginView CBV: logs in user and returns home page
- RegisterUser CBV: registers user credentials and returns login page
"""


#
# Home view included for testing.
# Is irrelevant and can be removed or replaced.
# Includes predecessor dependence from `accounts:urls` home url
#
class Home(generic.View, LoginRequiredMixin):
    template_name = 'accounts/index.html'

    def get(self, request):
        return render(request, self.template_name)


#
# User logout function
#
def logout_user(request):
    logout(request)

    return redirect('accounts:login')


#
# CBV gets and checks if email exists in the db
# Sends the user with the associated email a reset token
#
class PasswordResetRequest(generic.View):
    template_name = 'accounts/password-reset.html'
    email_template_name = 'accounts/reset.html'  # template containing reset token

    # Returns a blank password reset request form
    def get(self, request):
        form = PasswordResetForm()

        return render(request, self.template_name, {'form': form})

    # Verifies email and sends reset token to the entered address on success
    def post(self, request):
        form = PasswordResetForm(request.POST)
        current_site = get_current_site(request)  # Get the current sites protocol and domain name

        if form.is_valid():
            data = form.cleaned_data['email']

            # Check if email is associated with a user in the db
            associated_users = User.objects.filter(Q(email=data))

            if associated_users.exists():
                for user in associated_users:
                    subject = 'Password Reset Requested'
                    email_template_name = self.email_template_name
                    context = {
                        'email': user.email,
                        'domain': current_site,
                        'site_name': 'SimpleAuthentication',
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'user': user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, context)

                    # Send email to user address
                    try:
                        send_mail(
                            subject, email, settings.EMAIL_HOST_USER,
                            [user.email], fail_silently=False,
                        )
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')

                    # Redirect user to page notifying user of the sent mail
                    return redirect('accounts:password-reset-done')

            message = messages.add_message(
                request, messages.ERROR,
                'No such user associated with the email provided.'
            )
            return render(request, self.template_name, {'form': form, 'message': message})

        message = messages.add_message(
            request, messages.ERROR,
            'Error validating form.'
        )
        return render(request, self.template_name, {'form': form, 'message': message})


#
# CBV for user login
#
class LoginView(generic.View):
    template_name = 'accounts/login.html'

    # Returns a blank login form
    def get(self, request):
        form = UserLoginForm()

        return render(request, self.template_name, {'form': form})

    # Verifies email and password
    def post(self, request):
        form = UserLoginForm(request.POST)

        if form.is_valid:
            email = request.POST.get('email')
            password = request.POST.get('password')
            remember_me = request.POST.get('remember_me')
            user = authenticate(email=email, password=password)

            if user is not None:
                login(request, user)

                if remember_me:
                    # Set expiry to 2 weeks
                    request.session.set_expiry(1209600)
                else:
                    request.session.set_expiry(0)

                return render(request, 'accounts/index.html', {'user': user})

            else:
                message = 'Invalid Credentials!'

                return render(request, self.template_name, {'form': form, 'message': message})

        message = 'Error validating form'

        return render(request, self.template_name, {'form': form, 'message': message})


#
# CBV for user registration
#
class RegisterUser(generic.CreateView):
    template_name = 'accounts/register.html'

    # Returns a blank registration form
    def get(self, request, **kwargs):
        form = UserRegistrationForm()

        return render(request, self.template_name, {'form': form})

    # Validates credentials: email, username and password
    def post(self, request, **kwargs):
        form = UserRegistrationForm(request.POST)

        if form.is_valid():
            # Do not save data in db
            user = form.save(commit=False)
            msg = user.username + ' created successfully. Please login to continue.'
            messages.add_message(request, messages.SUCCESS, _(
                msg
            ))

            # Save data in db
            form.save(commit=True)

            # Redirect user to login page
            return redirect('accounts:login')

        message = messages.add_message(
            request, messages.ERROR, 'Failed to create account. Please contact your local administrator'
        )

        return render(request, self.template_name, {'form': form, 'message': message})

accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Unused Javascript and CSS from UIKit
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.xx.x/css/uikit.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/2.xx.x/js/uikit.min.js"></script>
    -->

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Font Awesome master -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/brands.min.css" integrity="sha512-OivR4OdSsE1onDm/i3J3Hpsm5GmOVvr9r49K3jJ0dnsxVzZgaOJ5MfxEAxCyGrzWozL9uJGKz6un3A7L+redIQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
{% block body %}
{% endblock %}

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->

</body>
</html>

accounts/templates/accounts/forms.html
{% load crispy_forms_tags %}
{% for field in form %}
<div class="form-outline mb-4">
    <!-- No need for error handling. It has already been taken up by
    another function.
    <div class="text-danger small">
        <span class="text-danger">{{ field.errors }}</span>
    </div>
    -->
    <div class="col-10">
        <p>{{ field | as_crispy_field }}</p>
    </div>
</div>
{% endfor %}

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}

{% block title %}Home{% endblock %}

{% block body %}
<h1>Welcome {{ user.username }}.</h1>
<h1>You have successfully logged in!</h1>

<a href="{% url 'accounts:logout' %}">Logout</a>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}login{% endblock %}

{% block body %}
<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                     class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form method="post">
                    {% csrf_token %}
                    <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start" style="padding-top: 10px">
                        <p class="lead fw-normal mb-0 me-3">Sign in with</p>
                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="fab fa-facebook-f"></i>
                        </button>

                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="fab fa-twitter"></i>
                        </button>

                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="fab fa-linkedin-in"></i>
                        </button>
                    </div>
                    <div class="divider d-flex align-items-center my-4">
                        <p class="text-center fw-bold mx-3 mb-0">Or</p>
                    </div>
                    {% include 'accounts/forms.html' %}
                    <button type="submit" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">Login
                    </button>
                </form>
                <hr>
                <div class="text-center">
                    <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account?
                        <a href="{% url 'accounts:register' %}" class="link-danger">Register</a>
                    </p>
                </div>
                <div class="text-center">
                    <a href="{% url 'accounts:password-reset' %}" class="text-body">Forgot Password</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/password-reset-complete.html
{% extends 'accounts/base.html' %}

{% block title %}Password Reset: Complete{% endblock %}

{% block body %}
<div class="container-fluid h-custom">
    <h2 class="lead mb-0">Reset Password</h2>
    <hr>
    <p>
        Your password has successfully been changed. Please
        <a href="{% url 'accounts:login' %}">log in</a> to continue
    </p>
</div>
{% endblock %}

accounts/templates/accounts/password-reset-confirm.html
{% extends 'accounts/base.html' %}

{% block title %}Password Reset: Confirm{% endblock %}

{% block body %}
<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                     class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form method="post">
                    {% csrf_token %}
                    {% include 'accounts/forms.html' %}
                    <button class="btn btn-primary btn-lg" type="submit"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">Reset Password
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/password-reset-sent.html
{% extends 'accounts/base.html' %}

{% block title %}Password Reset: Instruction{% endblock %}

{% block body %}
<div class="container-fluid h-custom">
    <h2 class="lead mb-0">Reset Password</h2>
    <hr>
    <p>Reset instructions have been sent to your email address.</p>
</div>
{% endblock %}

accounts/templates/accounts/password-reset.html
{% extends 'accounts/base.html' %}

{% block title %}Password Reset: Request{% endblock %}

{% block body %}
<section class="text-center">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                     class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <h2 class="lead mb-0"><b>Reset Your Password</b></h2>
                <br>
                <p class="lead mb-0">Forgot your password? Enter your email address.</p>
                <form method="post">
                    {% csrf_token %}
                    {% include 'accounts/forms.html' %}
                    <button type="submit" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">Send Email
                    </button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block title %}Register{% endblock %}

{% block body %}
<section class="text-center">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
                     class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
                <form method="post">
                    {% csrf_token %}
                    <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start"
                         style="padding-top: 10px">
                        <p class="lead fw-normal mb-0 me-3">Sign up with</p>
                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="fab fa-facebook-f"></i>
                        </button>

                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="fab fa-twitter"></i>
                        </button>

                        <button type="button" class="btn btn-primary btn-floating mx-1">
                            <i class="fab fa-linkedin-in"></i>
                        </button>
                    </div>
                    <div class="divider d-flex align-items-center my-4">
                        <p class="text-center fw-bold mx-3 mb-0">Or</p>
                    </div>

                    {% include 'accounts/forms.html' %}
                    <div class="small">
                        <input type="checkbox">
                        <label class="">Remember Me</label>
                    </div>
                    <button type="submit" class="btn btn-primary btn-lg"
                            style="padding-left: 2.5rem; padding-right: 2.5rem;">Create account
                    </button>
                </form>
                <div class="text-center">
                    <p class="small fw-bold mt-2 pt-1 mb-0">Already have an account?
                        <a href="{% url 'accounts:login' %}" class="link-danger">Sign-In</a>
                    </p>
                </div>
                <div class="text-center">
                    <a href="{% url 'accounts:password-reset' %}" class="text-body">Forgot Password</a>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}


accounts/templates/accounts/reset.html
{% autoescape off %}

Hello {{ user.username }},

We received a request to reset the password for your account associated with this Email Address.
To initiate the password reset process for your account, click the link below.

{{ protocol }}://{{ domain }}{% url 'accounts:password-reset-confirm' uidb64=uid token=token %}

This link can only be use once. If you need to reset your password again, please visit
{{ protocol }}://{{ domain }} and request another reset.

Sincerely,
The {{ site_name }} Team.

{% endautoescape %}